# Generated by Django 4.2.2 on 2023-07-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTaxi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=254)),
                ('to_location', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
