# Generated by Django 4.2.2 on 2023-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_taxi',
            field=models.BooleanField(default=False, verbose_name='Working'),
        ),
    ]
