# Generated by Django 4.2.2 on 2023-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_taxi',
            field=models.BooleanField(verbose_name='Working'),
        ),
    ]
