# Generated by Django 4.2.2 on 2023-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_taxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_taxi',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('is_user', 'User'), ('is_taxi', 'Taxi Driver')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
